# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memea', '0002_memea_datsegitkop'),
    ]

    operations = [
        migrations.AddField(
            model_name='memea',
            name='egilea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memea',
            name='ezdatsegitKop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memea',
            name='argazkia',
            field=models.FileField(upload_to=''),
        ),
    ]
