# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 21:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memea', '0003_auto_20161103_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='IruzkinPuntuazioa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuazioa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MemeIruzkina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iruzkina', models.CharField(max_length=300)),
                ('iruzkintzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('memea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memea.Memea')),
            ],
        ),
        migrations.CreateModel(
            name='MemePuntuazioa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuazioa', models.IntegerField()),
                ('memea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memea.Memea')),
                ('puntuatzailea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='iruzkinpuntuazioa',
            name='iruzkina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memea.MemeIruzkina'),
        ),
        migrations.AddField(
            model_name='iruzkinpuntuazioa',
            name='puntuatzailea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
